---
title: "Exploring Development Economics Through World Bank Data"
author: "Aldrich Wang"
output: github_document
---

## Load necessary libraries

```{r}
library(tidyverse)
library(here)
```

## Write a function to import the data files

```{r}
# create the import_data function
import_data <- function(file_path){
  # take in the .csv file
  data <- read_csv(here("data_world_bank", file_path), 
                   skip = 3) %>%
    select(-"Indicator Code") %>%
    pivot_longer(
      # tidy up the data and make indicator names on the first row
      cols = c(4:64),
      names_to = "year",
      values_to = "values"
    ) %>%
    pivot_wider(
      names_from = c("Indicator Name"),
      values_from = "values"
    ) %>%
    # convert variable into numeric type
    mutate(year = as.numeric(year))
  return(data)
}
```

## Import the data

```{r}
# import data frames in the data_world_bank file and merge them into one

# list .csv data files
merged_data <- list.files(here("data_world_bank"), pattern = "*.csv")
paste("data_world_bank", merged_data, sep="/")
# set the right directory
setwd("~/dev_econ_cohort_2022/data_world_bank")
# merge data frames into one
all_data <- plyr:::ldply(merged_data, import_data)  
```

## Data Work 

```{r}
# take a quick look at the data
glimpse(all_data)
```
